apiVersion: v2
description: Helm chart used to deploy a Hello World application to Kubernetes.
type: application
name: hello-world
home: https://github.com/rudisimo/helm-charts
version: 1.0.0
appVersion: 1.0.0
sources:
  - https://github.com/rudisimo/helm-charts
maintainers:
  - name: rudisimo
    email: rodolfo@puig.io
