{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hello-world.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hello-world.name" . }}
    app.kubernetes.io/component: app
    {{- include "hello-world.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hello-world.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: app
    {{- include "hello-world.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "hello-world.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "hello-world.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
