apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hello-world.name" . }}
    app.kubernetes.io/component: app
    {{- include "hello-world.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations  }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "hello-world.labels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.image }}
          image: "{{- if .repository -}}{{ .repository }}{{ else }}{{ .registry }}/{{ .image }}{{- end -}}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          args: []
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - name: http
            protocol: TCP
            containerPort: 8080
