name: Release

on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      manual_release:
        description: 'Manual Release'
        required: false
        type: boolean

jobs:
  changes:
    name: Calculate Changes
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Filter Changed Paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            docs:
              - 'docs/**/*'
              - 'README.md'
            charts:
              - 'charts/**/*'

  docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: changes
    if: (needs.changes.outputs.docs == 'true') || ${{ inputs.manual_release }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Documentation
        run: |
          npm install
          npm run build:docs
      - name: Deploy
        if: (github.ref == 'refs/heads/master')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ./dist
          publish_branch: gh-pages

  helm:
    name: Deploy Helm Charts
    runs-on: ubuntu-latest
    needs: changes
    if: (needs.changes.outputs.charts == 'true') || ${{ inputs.manual_release }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Configure Helm
        run: |
          bash -e <(curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3)
          helm version
          helm repo add stable https://charts.helm.sh/stable
          helm repo update
      - name: Deploy
        if: (github.ref == 'refs/heads/master')
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
          charts_repo_url: https://rudisimo.github.io/helm-charts/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"